### ISSUE TITLE
Rebuild with Anaconda 5.0 Compilers

### ISSUE THREAD

**Issue by ehsantn** [conda-forge/parquet-cpp-feedstock#37]
Anaconda 5.0 uses GCC 7.2 compiler: https://www.anaconda.com/blog/developer-blog/utilizing-the-new-compilers-in-anaconda-distribution-5/?lang=en-us

Because of this change, parquet-cpp fails (std string ABI error, etc.).

**Comment by xhochy** [comment]
@jakirkham What are the conda-forge plans for the new Anaconda chain?

**Comment by wesm** [comment]
Am I reading this right that Anaconda 5 breaks any conda-forge packages using the gcc 4.x ABI?

**Comment by ehsantn** [comment]
Yes.

**Comment by jakirkham** [comment]
We are planning on having a meeting in the next week or two to discuss the compiler situation in particular. It is tentatively scheduled for next Friday. If you are interested in attending, feel free to drop by (even if you just want to listen). Also there is a poll for the meeting date, would encourage you to include your availability should you want to attend just in case the date needs to shift. Details in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/460 ).

**Comment by ehsantn** [comment]
@jakirkham any updates?
